# Generated by Django 4.0.1 on 2022-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='view_count'),
        ),
    ]
