# Generated by Django 4.0.1 on 2022-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='VIEW_COUNT'),
        ),
    ]
